package langModel;

import static org.junit.Assert.*;

import java.util.HashMap;

import org.junit.Before;
import org.junit.Rule;
import org.junit.Test;
import org.junit.rules.TestName;


/**
 * This JUnit Test Class has been generated by right clicking on the NgramUtil class
 * and selecting "New > Junit Test Case". After that, you have to select the methods 
 * for which you would like to generate tests. 
 * In practice, you will duplicate manually the test methods to possibly create 
 * several tests for one method.
 * 
 * Your work is then to remove the fail parts and to implement each test.
 * One method is given as an example
 * 
 * To run them:
 * either right click on the class name or simply on the method name and
 * select "Run As Junit Test".
 * 
 * @author N. Hernandez and S. Quiniou (2015)
 *
 */
public class MyNgramCountsTest {
	MyNgramCounts ngramText = new MyNgramCounts();
	MyNgramCounts ngramFile = new MyNgramCounts();
	MyNgramCounts ngramRead = new MyNgramCounts();
	
	
	@Test
	public void testScanTextString() {
		String texte = "<s> bonjour </s>\n<s> Ce cours est enlisant </s>";
		ngramText.scanTextString(texte, 2);
		assertEquals(2, ngramText.getCounts("<s>"));
		assertEquals(2,ngramText.getMaximalOrder());
		assertEquals(9,ngramText.getTotalWordNumber());
		assertEquals(14,ngramText.getNgramCounterSize());
		ngramText.writeNgramCountFile("../data/train/ngramtest.txt");

	}

	@Test
	public void testScanTextFile(){
		ngramFile.scanTextFile("../data/train/sample-fr.txt",3);
		//<s> la phrase est la phrase est la phrase </s>
		//<s> un arbre dans la plaine pousse avec amour </s>
		assertEquals(2, ngramFile.getCounts("est la"));
		assertEquals(3,ngramFile.getMaximalOrder());
		assertEquals(20,ngramFile.getTotalWordNumber());
		assertEquals(39,ngramFile.getNgramCounterSize());
	}

	@Test
	public void testReadFile() {
		ngramRead.readNgramCountsFile("../data/train/ngramtest.txt");
		assertEquals(1, ngramRead.getCounts("bonjour"));
		assertEquals(2,ngramRead.getMaximalOrder());
		assertEquals(9,ngramRead.getTotalWordNumber());
		assertEquals(14,ngramRead.getNgramCounterSize());

	}



	

	
	
	/**
	 * The following code displays a separator 
	 * between each method output
	 * 
	 * (manually added)
	 **/
	@Rule
	public TestName name = new TestName();

	@Before
	public void printSeparator()
	{
		System.out.println("\n=== " + name.getMethodName() + " =====================");
	}

}
